# Generated by Django 6.0.1 on 2026-01-31 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='board.board')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('body_md', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('archived', 'Archivée')], default='active', max_length=12)),
                ('position', models.PositiveIntegerField(default=0)),
                ('impact', models.PositiveSmallIntegerField(default=0)),
                ('next_action', models.CharField(blank=True, max_length=200)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='board.column')),
                ('tags', models.ManyToManyField(blank=True, related_name='ideas', to='board.tag')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='uniq_column_name_per_board'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('board', 'order'), name='uniq_column_order_per_board'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['status'], name='board_idea_status_cc8bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['column', 'position'], name='board_idea_column__5df8c6_idx'),
        ),
    ]
