# Generated by Django 6.0.1 on 2026-02-07 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_ideatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='kind',
            field=models.CharField(choices=[('normal', 'Normale'), ('validated', 'Validée'), ('archived', 'Archivée')], default='normal', help_text='Rôle fonctionnel de la colonne (logique métier)', max_length=12),
        ),
        migrations.AddField(
            model_name='idea',
            name='converted_at',
            field=models.DateTimeField(blank=True, help_text="Date de conversion de l'idée en projet (si applicable).", null=True),
        ),
        migrations.CreateModel(
            name='IdeaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goals', models.TextField(blank=True, help_text='Objectifs (Markdown autorisé).')),
                ('scope', models.TextField(blank=True, help_text='Périmètre / inclusions-exclusions.')),
                ('definition_of_done', models.TextField(blank=True, help_text='Définition de terminé (DoD).')),
                ('due_date', models.DateField(blank=True, help_text='Échéance cible (optionnelle).', null=True)),
                ('idea', models.OneToOneField(help_text='Idea source de ce projet', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='board.idea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
